package iac.cud.infosweb.ws.classifierzip;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2014-06-03T17:51:56.121+04:00
 * Generated source version: 2.6.4
 * 
 */

// RSID: 20174
@WebService(targetNamespace = "http://ws.iac.spb.ru/ClassifierZip", name = "ClassifierZip")
@XmlSeeAlso({ObjectFactory.class, iac.cud.infosweb.ws.classif.common.ObjectFactory.class})
public interface ClassifierZip {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getClassifierByClassifierNameCUD", targetNamespace = "http://ws.iac.spb.ru/ClassifierZip", className = "ru.spb.iac.ws.classifierzip.GetClassifierByClassifierName")
    @WebMethod
    @ResponseWrapper(localName = "getClassifierByClassifierNameResponseCUD", targetNamespace = "http://ws.iac.spb.ru/ClassifierZip", className = "ru.spb.iac.ws.classifierzip.GetClassifierByClassifierNameResponse")
    public iac.cud.infosweb.ws.classifierzip.ResponseElement52 getClassifierByClassifierName(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "pass", targetNamespace = "")
        java.lang.String pass,
        @WebParam(name = "Fullname", targetNamespace = "")
        java.lang.String fullname,
        @WebParam(name = "ActualDoc", targetNamespace = "")
        int actualDoc
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getClassifierZipListByClassifierNameCUD", targetNamespace = "http://ws.iac.spb.ru/ClassifierZip", className = "ru.spb.iac.ws.classifierzip.GetClassifierZipListByClassifierName")
    @WebMethod
    @ResponseWrapper(localName = "getClassifierZipListByClassifierNameResponseCUD", targetNamespace = "http://ws.iac.spb.ru/ClassifierZip", className = "ru.spb.iac.ws.classifierzip.GetClassifierZipListByClassifierNameResponse")
    public iac.cud.infosweb.ws.classifierzip.ResponseElement54 getClassifierZipListByClassifierName(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "pass", targetNamespace = "")
        java.lang.String pass,
        @WebParam(name = "Fullname", targetNamespace = "")
        java.lang.String fullname
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getClassifierZipListByClassifierNumberCUD", targetNamespace = "http://ws.iac.spb.ru/ClassifierZip", className = "ru.spb.iac.ws.classifierzip.GetClassifierZipListByClassifierNumber")
    @WebMethod
    @ResponseWrapper(localName = "getClassifierZipListByClassifierNumberResponseCUD", targetNamespace = "http://ws.iac.spb.ru/ClassifierZip", className = "ru.spb.iac.ws.classifierzip.GetClassifierZipListByClassifierNumberResponse")
    public iac.cud.infosweb.ws.classifierzip.ResponseElement53 getClassifierZipListByClassifierNumber(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "pass", targetNamespace = "")
        java.lang.String pass,
        @WebParam(name = "RegNumber", targetNamespace = "")
        int regNumber
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getClassifierByClassifierNumberCUD", targetNamespace = "http://ws.iac.spb.ru/ClassifierZip", className = "ru.spb.iac.ws.classifierzip.GetClassifierByClassifierNumber")
    @WebMethod
    @ResponseWrapper(localName = "getClassifierByClassifierNumberResponseCUD", targetNamespace = "http://ws.iac.spb.ru/ClassifierZip", className = "ru.spb.iac.ws.classifierzip.GetClassifierByClassifierNumberResponse")
    public iac.cud.infosweb.ws.classifierzip.ResponseElement51 getClassifierByClassifierNumber(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "pass", targetNamespace = "")
        java.lang.String pass,
        @WebParam(name = "RegNumber", targetNamespace = "")
        int regNumber,
        @WebParam(name = "ActualDoc", targetNamespace = "")
        int actualDoc
    );
}
