package ru.spb.iac.cud.items.app;

public enum AppUserAttributesClassif {

	SURNAME_USER, NAME_USER, PATRONYMIC_USER, IOGV_CODE_USER, POSITION_USER, EMAIL_USER, PHONE_USER, CERTIFICATE_USER, NAME_DEPARTAMENT, NAME_ORG, IOGV_CODE_ORG, LOGIN_USER, PASSWORD_USER, UID_USER,
}
